# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    paths-ignore:
      - 'dev_logs/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'dev_logs/**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache gradle
      uses: actions/cache@v2.1.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      working-directory: ./app
      run: chmod +x ./gradlew
    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew build
